id = "package-swift"
name = "Package Swift LSP Extension"
version = "0.0.1"
schema_version = 1
authors = ["kattouf <vasiliy.kattouf@gmail.com"]
repository = "https://github.com/zed-extensions/package-swift"
